title: "Nico Fragale"
description: "Portfolio & Research Notes"
theme: minima

minima:
  skin: classic

header_pages:
  - projects/index.md
  - notes/index.md
  - now.md
  - about.md

google_analytics: 'G-2H76Y6GQQZ'
